added a ton of script

diff --git a/bin/linux/gentoo-update b/bin/linux/gentoo-update
--- a/bin/linux/gentoo-update
+++ b/bin/linux/gentoo-update
@@ -1,15 +1,27 @@
 #!/usr/bin/env bash
 
+#set -eoux pipefile
+
+home="/home/agge"
+
 # Must be ran with superuser privileges.
 if [[ $EUID -ne 0 ]]; then
-   echo "gentoo-update must be ran with superuser privileges."
-   exit 1
+	echo "$(basename "$0"): Must be ran with superuser privileges"
+	exit 1
 fi
+
+ret=0
 
 eix-sync # runs a bunch of sync commands, see gentoo cheatsheet
 emerge --oneshot sys-apps/portage # FIRST: make sure portage is up-to-date
 eclean-kernel --all # clean all BUT active kernel
+
 emerge --verbose --update --deep --newuse --keep-going @world
+ret=$?
+if [[ $ret -ne 0 ]]; then
+	echo "WARNING: $(basename "$0"): Update failed: $ret" 2>&1
+fi
+
 emerge --depclean # NOTE: doesn't ASK, be careful!
 
 # run all rebuilds after depclean
@@ -23,5 +35,21 @@ emerge @preserved-rebuild
 perl-cleaner --all # clean perl modules
 
 # Other unprivledged updates
+sudo -u agge flatpak update -y
 sudo -u agge nvim --headless "+Lazy! sync" +qa # update nvim headless
+# xxx update mason lsp
+
 #haskell-update # TODO: not working
+
+# update /opt
+sudo -u agge /usr/bin/env bash "$home/scripts/update/update-runelite.sh"
+
+# update priv
+sudo -u agge /usr/bin/env bash "$home/scripts/priv/update.sh"
+
+# cleanup
+emerge --depclean	# depclean if anything new created since last depclean
+eclean-dist --deep
+eclean-pkg
+
+# xxx clean-system
